# Form implementation generated from reading ui file 'pages\red_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from ui_files import resources_rc

from Customs.CustomLineEdit import CustomLineEdit
QtWidgets.QLineEdit = CustomLineEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        MainWindow.resize(608, 261)
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:#F0F0F0;\n"
"    font:bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:#555555;\n"
"    border:1px solid #555555;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/checked_square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"#red_header{\n"
"    color:#40E0D0;\n"
"    font:24px;\n"
"    padding:0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color:#101524;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_frame = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.widget_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_frame.setStyleSheet("QWidget[objectName=\"widget_frame\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:none;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#lbl_titlebar_text{\n"
"    font:12px;\n"
"}\n"
"\n"
"#btn_close_window{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"#btn_close_window:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_red.png\");\n"
"}\n"
"\n"
"#btn_close_window:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}")
        self.widget_frame.setObjectName("widget_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_titlebar_icon = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setText("")
        self.lbl_titlebar_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/F_Icon_1.png"))
        self.lbl_titlebar_icon.setScaledContents(True)
        self.lbl_titlebar_icon.setObjectName("lbl_titlebar_icon")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_icon)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lbl_titlebar_text = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_text.setMinimumSize(QtCore.QSize(110, 24))
        self.lbl_titlebar_text.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbl_titlebar_text.setObjectName("lbl_titlebar_text")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_text)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btn_close_window = QtWidgets.QPushButton(parent=self.widget_frame)
        self.btn_close_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setText("")
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_7.addWidget(self.btn_close_window)
        self.gridLayout_3.addWidget(self.widget_frame, 0, 0, 1, 1)
        self.red_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.red_header.setMinimumSize(QtCore.QSize(590, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.red_header.setFont(font)
        self.red_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.red_header.setObjectName("red_header")
        self.gridLayout_3.addWidget(self.red_header, 1, 0, 1, 1)
        self.red_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.red_text.setMinimumSize(QtCore.QSize(590, 25))
        self.red_text.setIndent(16)
        self.red_text.setObjectName("red_text")
        self.gridLayout_3.addWidget(self.red_text, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, 25, -1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_address = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_address.setMinimumSize(QtCore.QSize(75, 20))
        self.lbl_address.setMaximumSize(QtCore.QSize(75, 20))
        self.lbl_address.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_address.setObjectName("lbl_address")
        self.horizontalLayout_3.addWidget(self.lbl_address)
        self.lineEdit_address = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_address.setMinimumSize(QtCore.QSize(430, 25))
        self.lineEdit_address.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_address.setClearButtonEnabled(True)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout_3.addWidget(self.lineEdit_address)
        self.btn_openDialog_address = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_openDialog_address.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/open_file_dialog.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_openDialog_address.setIcon(icon)
        self.btn_openDialog_address.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setObjectName("btn_openDialog_address")
        self.horizontalLayout_3.addWidget(self.btn_openDialog_address)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(25, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.checkBox_deleteObjectsInSymlinks = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_deleteObjectsInSymlinks.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_deleteObjectsInSymlinks.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_deleteObjectsInSymlinks.setObjectName("checkBox_deleteObjectsInSymlinks")
        self.horizontalLayout_4.addWidget(self.checkBox_deleteObjectsInSymlinks)
        self.checkBox_recursive = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_recursive.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_recursive.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_recursive.setChecked(True)
        self.checkBox_recursive.setObjectName("checkBox_recursive")
        self.horizontalLayout_4.addWidget(self.checkBox_recursive)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3.addWidget(self.widget, 4, 0, 1, 1)
        self.widget_btn_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_btn_container.setMinimumSize(QtCore.QSize(430, 50))
        self.widget_btn_container.setStyleSheet("QWidget[objectName=\"widget_btn_container\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#40E0D0;\n"
"    border:2px solid #40E0D0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid #2BA699;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:#555555;\n"
"}")
        self.widget_btn_container.setObjectName("widget_btn_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_btn_container)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(303, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.btn_delete = QtWidgets.QPushButton(parent=self.widget_btn_container)
        self.btn_delete.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_delete.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_6.addWidget(self.btn_delete)
        self.gridLayout_3.addWidget(self.widget_btn_container, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RedWindow"))
        self.lbl_titlebar_text.setText(_translate("MainWindow", "Remove Empty Directories"))
        self.red_header.setText(_translate("MainWindow", "Remove Empty Directories"))
        self.red_text.setText(_translate("MainWindow", "Are you somehow left with empty directories? Let us help you get rid of them all."))
        self.lbl_address.setText(_translate("MainWindow", "Address:"))
        self.lineEdit_address.setPlaceholderText(_translate("MainWindow", "Select or drag and drop"))
        self.checkBox_deleteObjectsInSymlinks.setText(_translate("MainWindow", "Delete Objects in Symlinks"))
        self.checkBox_recursive.setText(_translate("MainWindow", "Recursive"))
        self.btn_delete.setText(_translate("MainWindow", "Delete Now"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
