# Form implementation generated from reading ui file 'C:\Users\fevzi\Downloads\pages\create_scenario_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from ui_files import resources_rc
from Customs.CustomLineEdit import CustomLineEdit

QtWidgets.QLineEdit = CustomLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        MainWindow.resize(864, 650)
        MainWindow.setMinimumSize(QtCore.QSize(864, 650))
        MainWindow.setStyleSheet("QScrollArea QWidget{\n"
"    background-color:#101524;\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border:none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color:#101524;\n"
"}\n"
"\n"
"QScrollBar::handle{\n"
"    background-color:#6B6B6B;\n"
"}\n"
"\n"
"QScrollBar::handle:pressed{\n"
"    background-color:#555555;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QScrollBar:horizontal{\n"
"    height: 10px;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    width: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_frame = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.widget_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_frame.setStyleSheet("QWidget[objectName=\"widget_frame\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:none;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#lbl_titlebar_text{\n"
"    font:12px;\n"
"}\n"
"\n"
"#btn_close_window{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"#btn_close_window:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_red.png\");\n"
"}\n"
"\n"
"#btn_close_window:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}")
        self.widget_frame.setObjectName("widget_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_titlebar_icon = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setText("")
        self.lbl_titlebar_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/F_Icon_1.png"))
        self.lbl_titlebar_icon.setScaledContents(True)
        self.lbl_titlebar_icon.setObjectName("lbl_titlebar_icon")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_icon)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lbl_titlebar_text = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_text.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_titlebar_text.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbl_titlebar_text.setObjectName("lbl_titlebar_text")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_text)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btn_close_window = QtWidgets.QPushButton(parent=self.widget_frame)
        self.btn_close_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setText("")
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_7.addWidget(self.btn_close_window)
        self.verticalLayout_3.addWidget(self.widget_frame)
        self.widget_header = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_header.setStyleSheet("QLabel{\n"
"    color:#FAFAFA;\n"
"    font:11px;\n"
"}")
        self.widget_header.setObjectName("widget_header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_header)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_hint_icon = QtWidgets.QLabel(parent=self.widget_header)
        self.lbl_hint_icon.setMinimumSize(QtCore.QSize(25, 25))
        self.lbl_hint_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.lbl_hint_icon.setText("")
        self.lbl_hint_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/hint_icon.png"))
        self.lbl_hint_icon.setScaledContents(True)
        self.lbl_hint_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_hint_icon.setObjectName("lbl_hint_icon")
        self.horizontalLayout_3.addWidget(self.lbl_hint_icon)
        self.lbl_hint = QtWidgets.QLabel(parent=self.widget_header)
        self.lbl_hint.setMinimumSize(QtCore.QSize(0, 38))
        self.lbl_hint.setMaximumSize(QtCore.QSize(16777215, 38))
        self.lbl_hint.setWordWrap(True)
        self.lbl_hint.setObjectName("lbl_hint")
        self.horizontalLayout_3.addWidget(self.lbl_hint)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_warning_icon = QtWidgets.QLabel(parent=self.widget_header)
        self.lbl_warning_icon.setMinimumSize(QtCore.QSize(22, 22))
        self.lbl_warning_icon.setMaximumSize(QtCore.QSize(22, 22))
        self.lbl_warning_icon.setText("")
        self.lbl_warning_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/disclaimer_red.png"))
        self.lbl_warning_icon.setScaledContents(True)
        self.lbl_warning_icon.setObjectName("lbl_warning_icon")
        self.horizontalLayout_4.addWidget(self.lbl_warning_icon)
        self.lbl_warning = QtWidgets.QLabel(parent=self.widget_header)
        self.lbl_warning.setMinimumSize(QtCore.QSize(0, 38))
        self.lbl_warning.setMaximumSize(QtCore.QSize(16777215, 38))
        self.lbl_warning.setWordWrap(True)
        self.lbl_warning.setObjectName("lbl_warning")
        self.horizontalLayout_4.addWidget(self.lbl_warning)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.widget_header)
        self.scrollArea_scenario_area = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea_scenario_area.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:#F0F0F0;\n"
"    font:bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:#555555;\n"
"    border:1px solid #555555;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/checked_square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"QSpinBox{\n"
"    background-color:#555555;\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QSpinBox:up-button{\n"
"    subcontrol-position:right;\n"
"    width:12px;\n"
"    height:12px;\n"
"    image:url(\":/yeniÖnek/fifsot_icons/up_arrow_white.png\");\n"
"}\n"
"\n"
"QSpinBox:up-button:hover{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/up_arrow_blue.png\");\n"
"}\n"
"\n"
"QSpinBox:down-button{\n"
"    subcontrol-position:left;\n"
"    width:12px;\n"
"    height:12px;\n"
"    image:url(\":/yeniÖnek/fifsot_icons/down_arrow_white.png\");\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    subcontrol-position:left;\n"
"    width:12px;\n"
"    height:12px;\n"
"    image:url(\":/yeniÖnek/fifsot_icons/down_arrow_blue.png\");\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #bbbcba;\n"
"    border: 2px solid #bbbcba;\n"
"    color: #000000;\n"
"    border-radius: 10px;\n"
"    padding-left: 5px;\n"
"    font: 11px;\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: #555555;\n"
"    color: #f0f0f0;\n"
"    padding: 5px;\n"
"    outline: 0px;\n"
"    border: 1px solid #555555;\n"
"}\n"
"QComboBox QListView::item:hover {\n"
"    background-color: #be8af9;\n"
"    color: #000000;\n"
"}\n"
"QComboBox QListView::item:selected {\n"
"    background-color: #be8af9;\n"
"    color: #000000;\n"
"}")
        self.scrollArea_scenario_area.setWidgetResizable(True)
        self.scrollArea_scenario_area.setObjectName("scrollArea_scenario_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 864, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_scenario_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea_scenario_area)
        self.widget_btn_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_btn_container.setMinimumSize(QtCore.QSize(430, 91))
        self.widget_btn_container.setMaximumSize(QtCore.QSize(16777215, 91))
        self.widget_btn_container.setStyleSheet("QWidget[objectName=\"widget_btn_container\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#40E0D0;\n"
"    border:2px solid #40E0D0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid #2BA699;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:#555555;\n"
"}\n"
"\n"
"#btn_add_transaction{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/add_2_blue.png\");\n"
"    background-color:transparent;\n"
"    border:1px solid transparent;\n"
"    border-radius:25px;\n"
"}\n"
"\n"
"#btn_add_transaction:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/add_2_lightBlue.png\");\n"
"    background-color:transparent;\n"
"    border:1px solid transparent;\n"
"    border-radius:25px;\n"
"}\n"
"\n"
"#btn_add_transaction:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/add_2_white.png\");\n"
"}\n"
"\n"
"#widget_add_btn_container{\n"
"    background-color:#101524;\n"
"}\n"
"\n"
"#lbl_saveName{\n"
"    color:#FAFAFA;\n"
"}\n"
"\n"
"#lineEdit_saveName{\n"
"    color:#FAFAFA;\n"
"    background-color:#606060;\n"
"    border:1px solid transparent;\n"
"    border-radius:5px;\n"
"    padding-left:5px;\n"
"    font:11px;\n"
"}\n"
"\n"
"#lineEdit_saveName:focus{\n"
"    border:1px solid #D1D1D1;\n"
"}")
        self.widget_btn_container.setObjectName("widget_btn_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_btn_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_add_btn_container = QtWidgets.QWidget(parent=self.widget_btn_container)
        self.widget_add_btn_container.setObjectName("widget_add_btn_container")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_add_btn_container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_add_transaction = QtWidgets.QPushButton(parent=self.widget_add_btn_container)
        self.btn_add_transaction.setMinimumSize(QtCore.QSize(51, 51))
        self.btn_add_transaction.setMaximumSize(QtCore.QSize(51, 51))
        self.btn_add_transaction.setText("")
        self.btn_add_transaction.setIconSize(QtCore.QSize(44, 44))
        self.btn_add_transaction.setObjectName("btn_add_transaction")
        self.horizontalLayout.addWidget(self.btn_add_transaction)
        spacerItem3 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_add_btn_container)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lbl_saveName = QtWidgets.QLabel(parent=self.widget_btn_container)
        self.lbl_saveName.setMinimumSize(QtCore.QSize(160, 25))
        self.lbl_saveName.setMaximumSize(QtCore.QSize(160, 25))
        self.lbl_saveName.setObjectName("lbl_saveName")
        self.horizontalLayout_2.addWidget(self.lbl_saveName)
        self.lineEdit_saveName = QtWidgets.QLineEdit(parent=self.widget_btn_container)
        self.lineEdit_saveName.setMinimumSize(QtCore.QSize(198, 25))
        self.lineEdit_saveName.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_saveName.setClearButtonEnabled(True)
        self.lineEdit_saveName.setObjectName("lineEdit_saveName")
        self.horizontalLayout_2.addWidget(self.lineEdit_saveName)
        self.btn_save = QtWidgets.QPushButton(parent=self.widget_btn_container)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_save.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.widget_btn_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_titlebar_text.setText(_translate("MainWindow", "Create New Scenario"))
        self.lbl_hint.setText(_translate("MainWindow", "Start by adding a new action. You can add as many actions as you want. In between, you can use the \'keep as temp\' feature to use temporary results and reference them."))
        self.lbl_warning.setText(_translate("MainWindow", "All parameter checks are performed during the scenario execution. To avoid serious errors, make sure that the parameters are correct. Always run the scenario on redundant files."))
        self.btn_add_transaction.setToolTip(_translate("MainWindow", "Add a new transaction"))
        self.lbl_saveName.setText(_translate("MainWindow", "Save Name (Must be unique!):"))
        self.lineEdit_saveName.setPlaceholderText(_translate("MainWindow", "Write here"))
        self.btn_save.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
