# Form implementation generated from reading ui file 'pages\create_symlink_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from ui_files import resources_rc

from Customs.CustomLineEdit import CustomLineEdit
QtWidgets.QLineEdit = CustomLineEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        MainWindow.resize(698, 330)
        MainWindow.setMinimumSize(QtCore.QSize(698, 300))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 330))
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:#F0F0F0;\n"
"    font:bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:#555555;\n"
"    border:1px solid #555555;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/checked_square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"#symlink_header{\n"
"    color:#40E0D0;\n"
"    font:24px;\n"
"    padding:0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color:#101524;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_frame = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.widget_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_frame.setStyleSheet("QWidget[objectName=\"widget_frame\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:none;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#lbl_titlebar_text{\n"
"    font:12px;\n"
"}\n"
"\n"
"#btn_close_window{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"#btn_close_window:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_red.png\");\n"
"}\n"
"\n"
"#btn_close_window:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}")
        self.widget_frame.setObjectName("widget_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_titlebar_icon = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setText("")
        self.lbl_titlebar_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/F_Icon_1.png"))
        self.lbl_titlebar_icon.setScaledContents(True)
        self.lbl_titlebar_icon.setObjectName("lbl_titlebar_icon")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_icon)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lbl_titlebar_text = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_text.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_titlebar_text.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbl_titlebar_text.setObjectName("lbl_titlebar_text")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_text)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btn_close_window = QtWidgets.QPushButton(parent=self.widget_frame)
        self.btn_close_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setText("")
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_7.addWidget(self.btn_close_window)
        self.gridLayout.addWidget(self.widget_frame, 0, 0, 1, 1)
        self.symlink_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.symlink_header.setMinimumSize(QtCore.QSize(590, 35))
        self.symlink_header.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.symlink_header.setFont(font)
        self.symlink_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.symlink_header.setObjectName("symlink_header")
        self.gridLayout.addWidget(self.symlink_header, 1, 0, 1, 1)
        self.symlink_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.symlink_text.setMinimumSize(QtCore.QSize(590, 25))
        self.symlink_text.setMaximumSize(QtCore.QSize(16777215, 25))
        self.symlink_text.setIndent(16)
        self.symlink_text.setObjectName("symlink_text")
        self.gridLayout.addWidget(self.symlink_text, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_source = QtWidgets.QLabel(parent=self.widget)
        self.lbl_source.setMinimumSize(QtCore.QSize(75, 20))
        self.lbl_source.setMaximumSize(QtCore.QSize(75, 20))
        self.lbl_source.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_source.setObjectName("lbl_source")
        self.horizontalLayout.addWidget(self.lbl_source)
        self.lineEdit_source = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_source.setMinimumSize(QtCore.QSize(430, 25))
        self.lineEdit_source.setClearButtonEnabled(True)
        self.lineEdit_source.setObjectName("lineEdit_source")
        self.horizontalLayout.addWidget(self.lineEdit_source)
        self.btn_openDialog_source = QtWidgets.QPushButton(parent=self.widget)
        self.btn_openDialog_source.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_source.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_source.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/open_file_dialog.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_openDialog_source.setIcon(icon)
        self.btn_openDialog_source.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_source.setObjectName("btn_openDialog_source")
        self.horizontalLayout.addWidget(self.btn_openDialog_source)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_destination = QtWidgets.QLabel(parent=self.widget)
        self.lbl_destination.setMinimumSize(QtCore.QSize(75, 20))
        self.lbl_destination.setMaximumSize(QtCore.QSize(75, 20))
        self.lbl_destination.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_destination.setObjectName("lbl_destination")
        self.horizontalLayout_2.addWidget(self.lbl_destination)
        self.lineEdit_destination = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_destination.setMinimumSize(QtCore.QSize(430, 25))
        self.lineEdit_destination.setClearButtonEnabled(True)
        self.lineEdit_destination.setObjectName("lineEdit_destination")
        self.horizontalLayout_2.addWidget(self.lineEdit_destination)
        self.btn_openDialog_destination = QtWidgets.QPushButton(parent=self.widget)
        self.btn_openDialog_destination.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_destination.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_destination.setText("")
        self.btn_openDialog_destination.setIcon(icon)
        self.btn_openDialog_destination.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_destination.setObjectName("btn_openDialog_destination")
        self.horizontalLayout_2.addWidget(self.btn_openDialog_destination)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_name = QtWidgets.QLabel(parent=self.widget)
        self.lbl_name.setMinimumSize(QtCore.QSize(75, 20))
        self.lbl_name.setMaximumSize(QtCore.QSize(75, 20))
        self.lbl_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout_3.addWidget(self.lbl_name)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(430, 25))
        self.lineEdit_name.setClearButtonEnabled(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_3.addWidget(self.lineEdit_name)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 1)
        self.widget_btn_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_btn_container.setMinimumSize(QtCore.QSize(430, 50))
        self.widget_btn_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_btn_container.setStyleSheet("QWidget[objectName=\"widget_btn_container\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#40E0D0;\n"
"    border:2px solid #40E0D0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid #2BA699;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:#555555;\n"
"}")
        self.widget_btn_container.setObjectName("widget_btn_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_btn_container)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(303, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.btn_create = QtWidgets.QPushButton(parent=self.widget_btn_container)
        self.btn_create.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_create.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout_6.addWidget(self.btn_create)
        self.gridLayout.addWidget(self.widget_btn_container, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SymlinkWindow"))
        self.lbl_titlebar_text.setText(_translate("MainWindow", "Create Symlink"))
        self.symlink_header.setText(_translate("MainWindow", "Create Symlink"))
        self.symlink_text.setText(_translate("MainWindow", "We can help you create symbolic links easily. Make sure to pay attention to the warnings."))
        self.lbl_source.setText(_translate("MainWindow", "Source:"))
        self.lineEdit_source.setPlaceholderText(_translate("MainWindow", "Select or drag and drop"))
        self.lbl_destination.setText(_translate("MainWindow", "Destination:"))
        self.lineEdit_destination.setPlaceholderText(_translate("MainWindow", "Select or drag and drop"))
        self.lbl_name.setText(_translate("MainWindow", "Name:"))
        self.lineEdit_name.setPlaceholderText(_translate("MainWindow", "--Compulsory-- (Specify extension if exists)"))
        self.btn_create.setText(_translate("MainWindow", "Create Now"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
