# Form implementation generated from reading ui file 'pages\whoIs_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from Customs.CustomLineEdit import CustomLineEdit
from ui_files import resources_rc

QtWidgets.QLineEdit = CustomLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        MainWindow.resize(717, 475)
        MainWindow.setMinimumSize(QtCore.QSize(698, 475))
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"#btn_detect{\n"
"    background-color:#40E0D0;\n"
"    border:2px solid #40E0D0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"#btn_detect:hover{\n"
"    border:2px solid #2BA699;\n"
"}\n"
"\n"
"#btn_detect:pressed{\n"
"    color:#555555;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:#F0F0F0;\n"
"    font:bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:#555555;\n"
"    border:1px solid #555555;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/checked_square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"#whoIs_header{\n"
"    color:#40E0D0;\n"
"    font:24px;\n"
"    padding:0px;\n"
"}\n"
"\n"
"#process_info_header{\n"
"    font:18px;\n"
"    padding:0px;\n"
"}\n"
"\n"
"#btn_terminate{\n"
"    background-color:#FFFFFF;\n"
"    border:2px solid #FFFFFF;\n"
"    border-radius:10px;\n"
"    color:#FF0000;\n"
"}\n"
"\n"
"#btn_terminate:hover{\n"
"    background-color:#FF0000;\n"
"    border:2px solid #FF0000;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#btn_terminate:pressed{\n"
"    border:2px solid #3B3B3B;\n"
"}\n"
"\n"
"#widget_btn_container{\n"
"    background-color:#3B3B3B;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color:#101524;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_frame = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.widget_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_frame.setStyleSheet("QWidget[objectName=\"widget_frame\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:none;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#lbl_titlebar_text{\n"
"    font:12px;\n"
"}\n"
"\n"
"#btn_close_window{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"#btn_close_window:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_red.png\");\n"
"}\n"
"\n"
"#btn_close_window:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}")
        self.widget_frame.setObjectName("widget_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_titlebar_icon = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setText("")
        self.lbl_titlebar_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/F_Icon_1.png"))
        self.lbl_titlebar_icon.setScaledContents(True)
        self.lbl_titlebar_icon.setObjectName("lbl_titlebar_icon")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_icon)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lbl_titlebar_text = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_text.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_titlebar_text.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbl_titlebar_text.setObjectName("lbl_titlebar_text")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_text)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btn_close_window = QtWidgets.QPushButton(parent=self.widget_frame)
        self.btn_close_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setText("")
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_7.addWidget(self.btn_close_window)
        self.verticalLayout_5.addWidget(self.widget_frame)
        self.whoIs_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.whoIs_header.setMinimumSize(QtCore.QSize(590, 35))
        self.whoIs_header.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.whoIs_header.setFont(font)
        self.whoIs_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.whoIs_header.setObjectName("whoIs_header")
        self.verticalLayout_5.addWidget(self.whoIs_header)
        self.whoIs_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.whoIs_text.setMinimumSize(QtCore.QSize(590, 25))
        self.whoIs_text.setMaximumSize(QtCore.QSize(16777215, 25))
        self.whoIs_text.setIndent(16)
        self.whoIs_text.setObjectName("whoIs_text")
        self.verticalLayout_5.addWidget(self.whoIs_text)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.whoIs_disclaimer_icon = QtWidgets.QLabel(parent=self.centralwidget)
        self.whoIs_disclaimer_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.whoIs_disclaimer_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.whoIs_disclaimer_icon.setText("")
        self.whoIs_disclaimer_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/disclaimer_red.png"))
        self.whoIs_disclaimer_icon.setScaledContents(True)
        self.whoIs_disclaimer_icon.setObjectName("whoIs_disclaimer_icon")
        self.horizontalLayout_10.addWidget(self.whoIs_disclaimer_icon)
        self.whoIs_disclaimer_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.whoIs_disclaimer_text.setMinimumSize(QtCore.QSize(550, 35))
        self.whoIs_disclaimer_text.setMaximumSize(QtCore.QSize(16777215, 35))
        self.whoIs_disclaimer_text.setWordWrap(True)
        self.whoIs_disclaimer_text.setObjectName("whoIs_disclaimer_text")
        self.horizontalLayout_10.addWidget(self.whoIs_disclaimer_text)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_address = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_address.setMinimumSize(QtCore.QSize(75, 20))
        self.lbl_address.setMaximumSize(QtCore.QSize(75, 20))
        self.lbl_address.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_address.setObjectName("lbl_address")
        self.horizontalLayout.addWidget(self.lbl_address)
        self.lineEdit_address = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_address.setMinimumSize(QtCore.QSize(430, 25))
        self.lineEdit_address.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_address.setClearButtonEnabled(True)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout.addWidget(self.lineEdit_address)
        self.btn_openDialog_address = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_openDialog_address.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/open_file_dialog.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_openDialog_address.setIcon(icon)
        self.btn_openDialog_address.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setObjectName("btn_openDialog_address")
        self.horizontalLayout.addWidget(self.btn_openDialog_address)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.btn_detect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_detect.setMinimumSize(QtCore.QSize(50, 25))
        self.btn_detect.setMaximumSize(QtCore.QSize(50, 25))
        self.btn_detect.setObjectName("btn_detect")
        self.horizontalLayout_2.addWidget(self.btn_detect)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, -1, 0, -1)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.whoIs_hint_icon = QtWidgets.QLabel(parent=self.centralwidget)
        self.whoIs_hint_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.whoIs_hint_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.whoIs_hint_icon.setText("")
        self.whoIs_hint_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/hint_icon.png"))
        self.whoIs_hint_icon.setScaledContents(True)
        self.whoIs_hint_icon.setObjectName("whoIs_hint_icon")
        self.horizontalLayout_11.addWidget(self.whoIs_hint_icon)
        self.lbl_info = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_info.setMinimumSize(QtCore.QSize(620, 35))
        self.lbl_info.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lbl_info.setWordWrap(True)
        self.lbl_info.setIndent(0)
        self.lbl_info.setObjectName("lbl_info")
        self.horizontalLayout_11.addWidget(self.lbl_info)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5.addWidget(self.frame)
        self.process_info_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.process_info_header.setMinimumSize(QtCore.QSize(590, 35))
        self.process_info_header.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.process_info_header.setFont(font)
        self.process_info_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.process_info_header.setObjectName("process_info_header")
        self.verticalLayout_5.addWidget(self.process_info_header)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(681, 70))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 151))
        self.stackedWidget.setStyleSheet("#stackedWidget #page_start, #page_info, #page_loading{\n"
"    background-color:#101524;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_start = QtWidgets.QWidget()
        self.page_start.setObjectName("page_start")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_start)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_start_icon = QtWidgets.QLabel(parent=self.page_start)
        self.lbl_start_icon.setMinimumSize(QtCore.QSize(32, 32))
        self.lbl_start_icon.setMaximumSize(QtCore.QSize(32, 32))
        self.lbl_start_icon.setText("")
        self.lbl_start_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/get_started_1_blue.png"))
        self.lbl_start_icon.setScaledContents(True)
        self.lbl_start_icon.setObjectName("lbl_start_icon")
        self.horizontalLayout_3.addWidget(self.lbl_start_icon)
        self.lbl_start_text = QtWidgets.QLabel(parent=self.page_start)
        self.lbl_start_text.setMinimumSize(QtCore.QSize(400, 32))
        self.lbl_start_text.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lbl_start_text.setScaledContents(False)
        self.lbl_start_text.setWordWrap(True)
        self.lbl_start_text.setObjectName("lbl_start_text")
        self.horizontalLayout_3.addWidget(self.lbl_start_text)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_start)
        self.page_info = QtWidgets.QWidget()
        self.page_info.setObjectName("page_info")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_info)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_process_name_header = QtWidgets.QLabel(parent=self.page_info)
        self.lbl_process_name_header.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_process_name_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_process_name_header.setObjectName("lbl_process_name_header")
        self.verticalLayout_2.addWidget(self.lbl_process_name_header)
        self.lbl_process_name = QtWidgets.QLabel(parent=self.page_info)
        self.lbl_process_name.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_process_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_process_name.setObjectName("lbl_process_name")
        self.verticalLayout_2.addWidget(self.lbl_process_name)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_process_id_header = QtWidgets.QLabel(parent=self.page_info)
        self.lbl_process_id_header.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_process_id_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_process_id_header.setObjectName("lbl_process_id_header")
        self.verticalLayout_3.addWidget(self.lbl_process_id_header)
        self.lbl_process_id = QtWidgets.QLabel(parent=self.page_info)
        self.lbl_process_id.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_process_id.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_process_id.setObjectName("lbl_process_id")
        self.verticalLayout_3.addWidget(self.lbl_process_id)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_info)
        self.page_loading = QtWidgets.QWidget()
        self.page_loading.setObjectName("page_loading")
        self.gridLayout = QtWidgets.QGridLayout(self.page_loading)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbl_loading_icon = QtWidgets.QLabel(parent=self.page_loading)
        self.lbl_loading_icon.setMinimumSize(QtCore.QSize(32, 32))
        self.lbl_loading_icon.setMaximumSize(QtCore.QSize(32, 32))
        self.lbl_loading_icon.setText("")
        self.lbl_loading_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/get_started_1_blue.png"))
        self.lbl_loading_icon.setScaledContents(True)
        self.lbl_loading_icon.setObjectName("lbl_loading_icon")
        self.horizontalLayout_9.addWidget(self.lbl_loading_icon)
        self.lbl_loading_text = QtWidgets.QLabel(parent=self.page_loading)
        self.lbl_loading_text.setMinimumSize(QtCore.QSize(260, 32))
        self.lbl_loading_text.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lbl_loading_text.setScaledContents(False)
        self.lbl_loading_text.setWordWrap(True)
        self.lbl_loading_text.setObjectName("lbl_loading_text")
        self.horizontalLayout_9.addWidget(self.lbl_loading_text)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem13 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_loading)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.widget_btn_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_btn_container.setMinimumSize(QtCore.QSize(590, 50))
        self.widget_btn_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_btn_container.setObjectName("widget_btn_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_btn_container)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.lbl_not_recommended = QtWidgets.QLabel(parent=self.widget_btn_container)
        self.lbl_not_recommended.setObjectName("lbl_not_recommended")
        self.horizontalLayout_6.addWidget(self.lbl_not_recommended)
        self.btn_terminate = QtWidgets.QPushButton(parent=self.widget_btn_container)
        self.btn_terminate.setMinimumSize(QtCore.QSize(80, 24))
        self.btn_terminate.setMaximumSize(QtCore.QSize(80, 24))
        self.btn_terminate.setObjectName("btn_terminate")
        self.horizontalLayout_6.addWidget(self.btn_terminate)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_btn_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WhoIs?"))
        self.lbl_titlebar_text.setText(_translate("MainWindow", "WhoIs?"))
        self.whoIs_header.setText(_translate("MainWindow", "WhoIs?"))
        self.whoIs_text.setText(_translate("MainWindow", "Find the processes that are using your files and keeping them open. You can terminate them if you want."))
        self.whoIs_disclaimer_text.setText(_translate("MainWindow", "Terminating a running process may have some unintended outcomes including data loss, system instability, programs crashing due to lost access a required resource."))
        self.lbl_address.setText(_translate("MainWindow", "Address:"))
        self.lineEdit_address.setPlaceholderText(_translate("MainWindow", "Select or drag and drop"))
        self.btn_detect.setText(_translate("MainWindow", "Detect"))
        self.lbl_info.setText(_translate("MainWindow", "This process may take some time depending on the number of programs open on your computer and the resources they use. We will not perform any action on the process until you see the process information."))
        self.process_info_header.setText(_translate("MainWindow", "Process Information"))
        self.lbl_start_text.setText(_translate("MainWindow", "Here is empty for now. Let\'s start by giving the file path and detecting the relevant process."))
        self.lbl_process_name_header.setText(_translate("MainWindow", "Process Name"))
        self.lbl_process_name.setText(_translate("MainWindow", "None"))
        self.lbl_process_id_header.setText(_translate("MainWindow", "Process ID"))
        self.lbl_process_id.setText(_translate("MainWindow", "None"))
        self.lbl_loading_text.setText(_translate("MainWindow", "We\'re working on it, it may take some time."))
        self.lbl_not_recommended.setText(_translate("MainWindow", "(Not recommended!)"))
        self.btn_terminate.setText(_translate("MainWindow", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
