# Form implementation generated from reading ui file 'pages\create_archive_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from ui_files import resources_rc

from Customs.CustomLineEdit import CustomLineEdit
QtWidgets.QLineEdit = CustomLineEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        MainWindow.resize(763, 280)
        MainWindow.setMinimumSize(QtCore.QSize(698, 280))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 350))
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:#F0F0F0;\n"
"    font:bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:#555555;\n"
"    border:1px solid #555555;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"#rename_header{\n"
"    color:#40E0D0;\n"
"    font:24px;\n"
"    padding:0px;\n"
"}\n"
"\n"
"#comboBox_format{\n"
"    background-color:#555555;\n"
"    color:#F0F0F0;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"#comboBox_format QAbstractItemView::item{\n"
"    min-height:30px;\n"
"}\n"
"\n"
"#comboBox_format::drop-down{\n"
"    border:none;\n"
"}\n"
"\n"
"#comboBox_format::down-arrow{\n"
"    background-color:transparent;\n"
"    image:url(\":/yeniÖnek/fifsot_icons/down_arrow_blue.png\");\n"
"    width:12px;\n"
"    height:12px;\n"
"    padding-right:5px;\n"
"}\n"
"\n"
"#comboBox_format::down-arrow:on{\n"
"    background-color:transparent;\n"
"    image:url(\":/yeniÖnek/fifsot_icons/up_arrow_blue.png\");\n"
"    width:12px;\n"
"    height:12px;\n"
"    padding-right:5px;\n"
"}\n"
"\n"
"#comboBox_format QListView{\n"
"    background-color:#555555;\n"
"    selection-color:#000000;\n"
"    selection-background-color:#40E0D0;\n"
"    color:#F0F0F0;\n"
"    padding:5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color:#101524;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_frame = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_frame.setMinimumSize(QtCore.QSize(698, 42))
        self.widget_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_frame.setStyleSheet("QWidget[objectName=\"widget_frame\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:none;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#lbl_titlebar_text{\n"
"    font:12px;\n"
"}\n"
"\n"
"#btn_close_window{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"#btn_close_window:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_red.png\");\n"
"}\n"
"\n"
"#btn_close_window:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}")
        self.widget_frame.setObjectName("widget_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_titlebar_icon = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setText("")
        self.lbl_titlebar_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/F_Icon_1.png"))
        self.lbl_titlebar_icon.setScaledContents(True)
        self.lbl_titlebar_icon.setObjectName("lbl_titlebar_icon")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_icon)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lbl_titlebar_text = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_text.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_titlebar_text.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbl_titlebar_text.setObjectName("lbl_titlebar_text")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_text)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btn_close_window = QtWidgets.QPushButton(parent=self.widget_frame)
        self.btn_close_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setText("")
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_7.addWidget(self.btn_close_window)
        self.gridLayout.addWidget(self.widget_frame, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_archiveAddress = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_archiveAddress.setMinimumSize(QtCore.QSize(230, 25))
        self.lbl_archiveAddress.setMaximumSize(QtCore.QSize(230, 25))
        self.lbl_archiveAddress.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_archiveAddress.setObjectName("lbl_archiveAddress")
        self.horizontalLayout.addWidget(self.lbl_archiveAddress)
        self.lineEdit_archiveAddress = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_archiveAddress.setMinimumSize(QtCore.QSize(280, 25))
        self.lineEdit_archiveAddress.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_archiveAddress.setText("")
        self.lineEdit_archiveAddress.setClearButtonEnabled(True)
        self.lineEdit_archiveAddress.setObjectName("lineEdit_archiveAddress")
        self.horizontalLayout.addWidget(self.lineEdit_archiveAddress)
        self.btn_openDialog_archiveAddress = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_openDialog_archiveAddress.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_archiveAddress.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_archiveAddress.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/open_file_dialog.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_openDialog_archiveAddress.setIcon(icon)
        self.btn_openDialog_archiveAddress.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_archiveAddress.setObjectName("btn_openDialog_archiveAddress")
        self.horizontalLayout.addWidget(self.btn_openDialog_archiveAddress)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_archiveName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_archiveName.setMinimumSize(QtCore.QSize(230, 25))
        self.lbl_archiveName.setMaximumSize(QtCore.QSize(230, 25))
        self.lbl_archiveName.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_archiveName.setObjectName("lbl_archiveName")
        self.horizontalLayout_5.addWidget(self.lbl_archiveName)
        self.lineEdit_archiveName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_archiveName.setMinimumSize(QtCore.QSize(280, 25))
        self.lineEdit_archiveName.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_archiveName.setText("")
        self.lineEdit_archiveName.setClearButtonEnabled(True)
        self.lineEdit_archiveName.setObjectName("lineEdit_archiveName")
        self.horizontalLayout_5.addWidget(self.lineEdit_archiveName)
        spacerItem2 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_rootDirectory = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_rootDirectory.setMinimumSize(QtCore.QSize(230, 25))
        self.lbl_rootDirectory.setMaximumSize(QtCore.QSize(230, 25))
        self.lbl_rootDirectory.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_rootDirectory.setObjectName("lbl_rootDirectory")
        self.horizontalLayout_2.addWidget(self.lbl_rootDirectory)
        self.lineEdit_rootDirectory = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_rootDirectory.setMinimumSize(QtCore.QSize(394, 25))
        self.lineEdit_rootDirectory.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_rootDirectory.setClearButtonEnabled(True)
        self.lineEdit_rootDirectory.setObjectName("lineEdit_rootDirectory")
        self.horizontalLayout_2.addWidget(self.lineEdit_rootDirectory)
        self.btn_openDialog_rootDirectory = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_openDialog_rootDirectory.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_rootDirectory.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_rootDirectory.setText("")
        self.btn_openDialog_rootDirectory.setIcon(icon)
        self.btn_openDialog_rootDirectory.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_rootDirectory.setObjectName("btn_openDialog_rootDirectory")
        self.horizontalLayout_2.addWidget(self.btn_openDialog_rootDirectory)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_baseDirectory = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_baseDirectory.setMinimumSize(QtCore.QSize(230, 25))
        self.lbl_baseDirectory.setMaximumSize(QtCore.QSize(230, 25))
        self.lbl_baseDirectory.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_baseDirectory.setObjectName("lbl_baseDirectory")
        self.horizontalLayout_3.addWidget(self.lbl_baseDirectory)
        self.lineEdit_baseDirectory = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_baseDirectory.setMinimumSize(QtCore.QSize(394, 25))
        self.lineEdit_baseDirectory.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_baseDirectory.setClearButtonEnabled(True)
        self.lineEdit_baseDirectory.setObjectName("lineEdit_baseDirectory")
        self.horizontalLayout_3.addWidget(self.lineEdit_baseDirectory)
        self.btn_openDialog_baseDirectory = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_openDialog_baseDirectory.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_baseDirectory.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_baseDirectory.setText("")
        self.btn_openDialog_baseDirectory.setIcon(icon)
        self.btn_openDialog_baseDirectory.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_baseDirectory.setObjectName("btn_openDialog_baseDirectory")
        self.horizontalLayout_3.addWidget(self.btn_openDialog_baseDirectory)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_format = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_format.setMinimumSize(QtCore.QSize(230, 25))
        self.lbl_format.setMaximumSize(QtCore.QSize(230, 25))
        self.lbl_format.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_format.setObjectName("lbl_format")
        self.horizontalLayout_4.addWidget(self.lbl_format)
        self.comboBox_format = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_format.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox_format.setMaximumSize(QtCore.QSize(100, 25))
        self.comboBox_format.setObjectName("comboBox_format")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_format)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.widget_btn_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_btn_container.setMinimumSize(QtCore.QSize(698, 50))
        self.widget_btn_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_btn_container.setStyleSheet("QWidget[objectName=\"widget_btn_container\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#40E0D0;\n"
"    border:2px solid #40E0D0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid #2BA699;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:#555555;\n"
"}")
        self.widget_btn_container.setObjectName("widget_btn_container")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_btn_container)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(303, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.btn_create = QtWidgets.QPushButton(parent=self.widget_btn_container)
        self.btn_create.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_create.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout_11.addWidget(self.btn_create)
        self.gridLayout.addWidget(self.widget_btn_container, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ArchiveWindow"))
        self.lbl_titlebar_text.setText(_translate("MainWindow", "Create Archive"))
        self.lbl_archiveAddress.setText(_translate("MainWindow", "Archive Address:"))
        self.lineEdit_archiveAddress.setPlaceholderText(_translate("MainWindow", "Select or drag and drop"))
        self.lbl_archiveName.setText(_translate("MainWindow", "Archive Name (Without Any Extension):"))
        self.lineEdit_archiveName.setPlaceholderText(_translate("MainWindow", "--Compulsory--"))
        self.lbl_rootDirectory.setText(_translate("MainWindow", "Root Directory:"))
        self.lineEdit_rootDirectory.setPlaceholderText(_translate("MainWindow", "Select or drag and drop"))
        self.lbl_baseDirectory.setText(_translate("MainWindow", "Base Directory:"))
        self.lineEdit_baseDirectory.setPlaceholderText(_translate("MainWindow", "Select or drag and drop, not compulsory"))
        self.lbl_format.setText(_translate("MainWindow", "Format:"))
        self.comboBox_format.setItemText(0, _translate("MainWindow", "zip"))
        self.comboBox_format.setItemText(1, _translate("MainWindow", "tar"))
        self.comboBox_format.setItemText(2, _translate("MainWindow", "gztar"))
        self.comboBox_format.setItemText(3, _translate("MainWindow", "bztar"))
        self.comboBox_format.setItemText(4, _translate("MainWindow", "xztar"))
        self.btn_create.setText(_translate("MainWindow", "Create Now"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
