# Form implementation generated from reading ui file 'C:\Users\fevzi\Downloads\pages\main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from ui_files import resources_rc

from Customs.CustomLineEdit import CustomLineEdit
QtWidgets.QLineEdit = CustomLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        MainWindow.resize(844, 630)
        MainWindow.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#555555;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_close_window\"]{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_close_window\"]:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_red.png\");\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_close_window\"]:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_expand_window\"]{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/expand_2_white.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_expand_window\"]:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/expand_2_blue.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_expand_window\"]:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/expand_2_white.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_minimize_window\"]{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/down_arrow_2_white.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_minimize_window\"]:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/down_arrow_2_blue.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_minimize_window\"]:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/down_arrow_2_white.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_menu_window\"]{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/dot_menu_white.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_menu_window\"]:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/dot_menu_blue.png\")\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_menu_window\"]:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/dot_menu_white.png\")\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/radio_checked_blue.png\");\n"
"    width:13px;\n"
"    height:13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/radio_unchecked_blue.png\");\n"
"    width:13px;\n"
"    height:13px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color:#555555;\n"
"}\n"
"\n"
"QScrollBar::handle{\n"
"    background-color:#6B6B6B;\n"
"}\n"
"\n"
"QScrollBar::handle:pressed{\n"
"    background-color:#555555;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QScrollBar:horizontal{\n"
"    height: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_frame = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.widget_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_frame.setStyleSheet("QWidget[objectName=\"widget_frame\"]{\n"
"    background-color:#3B3B3B;\n"
"    background-color:#101524;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:none;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#lbl_titlebar_text{\n"
"    font:12px;\n"
"}")
        self.widget_frame.setObjectName("widget_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_titlebar_icon = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setText("")
        self.lbl_titlebar_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/F_Icon_1.png"))
        self.lbl_titlebar_icon.setScaledContents(True)
        self.lbl_titlebar_icon.setObjectName("lbl_titlebar_icon")
        self.horizontalLayout.addWidget(self.lbl_titlebar_icon)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_titlebar_text = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_text.setMinimumSize(QtCore.QSize(110, 24))
        self.lbl_titlebar_text.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbl_titlebar_text.setObjectName("lbl_titlebar_text")
        self.horizontalLayout.addWidget(self.lbl_titlebar_text)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(parent=self.widget_frame)
        self.widget.setMinimumSize(QtCore.QSize(150, 25))
        self.widget.setMaximumSize(QtCore.QSize(150, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_menu_window = QtWidgets.QPushButton(parent=self.widget)
        self.btn_menu_window.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_menu_window.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_menu_window.setText("")
        self.btn_menu_window.setIconSize(QtCore.QSize(12, 12))
        self.btn_menu_window.setObjectName("btn_menu_window")
        self.horizontalLayout_11.addWidget(self.btn_menu_window)
        self.btn_minimize_window = QtWidgets.QPushButton(parent=self.widget)
        self.btn_minimize_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_minimize_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_minimize_window.setText("")
        self.btn_minimize_window.setIconSize(QtCore.QSize(12, 12))
        self.btn_minimize_window.setObjectName("btn_minimize_window")
        self.horizontalLayout_11.addWidget(self.btn_minimize_window)
        self.btn_expand_window = QtWidgets.QPushButton(parent=self.widget)
        self.btn_expand_window.setMinimumSize(QtCore.QSize(22, 22))
        self.btn_expand_window.setMaximumSize(QtCore.QSize(22, 22))
        self.btn_expand_window.setText("")
        self.btn_expand_window.setIconSize(QtCore.QSize(20, 20))
        self.btn_expand_window.setObjectName("btn_expand_window")
        self.horizontalLayout_11.addWidget(self.btn_expand_window)
        self.btn_close_window = QtWidgets.QPushButton(parent=self.widget)
        self.btn_close_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setText("")
        self.btn_close_window.setIconSize(QtCore.QSize(16, 16))
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_11.addWidget(self.btn_close_window)
        self.horizontalLayout.addWidget(self.widget)
        self.gridLayout_4.addWidget(self.widget_frame, 0, 0, 1, 3)
        self.widget_short_menu = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_short_menu.setMinimumSize(QtCore.QSize(61, 451))
        self.widget_short_menu.setMaximumSize(QtCore.QSize(61, 16777215))
        self.widget_short_menu.setStyleSheet("QWidget[objectName=\"widget_short_menu\"]{\n"
"    background-color:#101524;\n"
"}\n"
"\n"
"#btn_short_menu_menu{\n"
"    background-color:none;\n"
"    padding:10px;\n"
"    border:none;\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/Menu_Icon_2.png\");\n"
"}\n"
"\n"
"#btn_short_menu_menu:hover{\n"
"    background-color:none;\n"
"    padding:10px;\n"
"    border:none;\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/menu_clicked.png\");\n"
"}\n"
"\n"
"#lbl_short_menu_header{\n"
"    color:#FFFFFF;\n"
"    background-color:none;\n"
"    font:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:#F0F0F0;\n"
"    background-color:transparent;\n"
"    text-align:left;\n"
"    padding-left:12px;\n"
"    border-radius:0px;\n"
"    border-left:2px solid transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-left:2px solid #40E0D0;\n"
"}")
        self.widget_short_menu.setObjectName("widget_short_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_short_menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_short_menu_menu = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_menu.setMinimumSize(QtCore.QSize(41, 31))
        self.btn_short_menu_menu.setMaximumSize(QtCore.QSize(41, 31))
        self.btn_short_menu_menu.setText("")
        self.btn_short_menu_menu.setIconSize(QtCore.QSize(24, 24))
        self.btn_short_menu_menu.setObjectName("btn_short_menu_menu")
        self.horizontalLayout_10.addWidget(self.btn_short_menu_menu)
        spacerItem2 = QtWidgets.QSpacerItem(40, 38, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget_short_menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5.addWidget(self.frame_2)
        self.btn_short_menu_copy = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_copy.setMinimumSize(QtCore.QSize(31, 31))
        self.btn_short_menu_copy.setMaximumSize(QtCore.QSize(31, 31))
        self.btn_short_menu_copy.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/copy_files.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_copy.setIcon(icon)
        self.btn_short_menu_copy.setObjectName("btn_short_menu_copy")
        self.verticalLayout_5.addWidget(self.btn_short_menu_copy)
        self.btn_short_menu_delete = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_delete.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_delete.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_delete.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_delete.setIcon(icon1)
        self.btn_short_menu_delete.setObjectName("btn_short_menu_delete")
        self.verticalLayout_5.addWidget(self.btn_short_menu_delete)
        self.btn_short_menu_red = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_red.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_red.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_red.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/remove_directory.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_red.setIcon(icon2)
        self.btn_short_menu_red.setObjectName("btn_short_menu_red")
        self.verticalLayout_5.addWidget(self.btn_short_menu_red)
        self.btn_short_menu_rename = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_rename.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_rename.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_rename.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/rename.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_rename.setIcon(icon3)
        self.btn_short_menu_rename.setObjectName("btn_short_menu_rename")
        self.verticalLayout_5.addWidget(self.btn_short_menu_rename)
        self.btn_short_menu_count = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_count.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_count.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_count.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/count_1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_count.setIcon(icon4)
        self.btn_short_menu_count.setObjectName("btn_short_menu_count")
        self.verticalLayout_5.addWidget(self.btn_short_menu_count)
        self.btn_short_menu_symlinks = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_symlinks.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_symlinks.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_symlinks.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/symlink.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_symlinks.setIcon(icon5)
        self.btn_short_menu_symlinks.setObjectName("btn_short_menu_symlinks")
        self.verticalLayout_5.addWidget(self.btn_short_menu_symlinks)
        self.btn_short_menu_whoIs = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_whoIs.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_whoIs.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_whoIs.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_whoIs.setIcon(icon6)
        self.btn_short_menu_whoIs.setObjectName("btn_short_menu_whoIs")
        self.verticalLayout_5.addWidget(self.btn_short_menu_whoIs)
        self.btn_short_menu_archive = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_archive.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_archive.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_archive.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/archive_1_blue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_archive.setIcon(icon7)
        self.btn_short_menu_archive.setObjectName("btn_short_menu_archive")
        self.verticalLayout_5.addWidget(self.btn_short_menu_archive)
        self.btn_short_menu_scenario = QtWidgets.QPushButton(parent=self.widget_short_menu)
        self.btn_short_menu_scenario.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_short_menu_scenario.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_short_menu_scenario.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/scenario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_short_menu_scenario.setIcon(icon8)
        self.btn_short_menu_scenario.setObjectName("btn_short_menu_scenario")
        self.verticalLayout_5.addWidget(self.btn_short_menu_scenario)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.gridLayout_4.addWidget(self.widget_short_menu, 1, 0, 3, 1)
        self.widget_long_menu = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_long_menu.setMinimumSize(QtCore.QSize(171, 451))
        self.widget_long_menu.setMaximumSize(QtCore.QSize(171, 16777215))
        self.widget_long_menu.setStyleSheet("QWidget[objectName=\"widget_long_menu\"]{\n"
"    background-color:#101524;\n"
"}\n"
"\n"
"#btn_long_menu_menu{\n"
"    background-color:none;\n"
"    padding:10px;\n"
"    border:none;\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/Menu_Icon_2.png\");\n"
"}\n"
"\n"
"#btn_long_menu_menu:hover{\n"
"    background-color:none;\n"
"    padding:10px;\n"
"    border:none;\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/menu_clicked.png\");\n"
"}\n"
"\n"
"#lbl_long_menu_header{\n"
"    color:#FFFFFF;\n"
"    background-color:none;\n"
"    font:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:#F0F0F0;\n"
"    background-color:#2b3247;\n"
"    background-color:transparent;\n"
"    text-align:left;\n"
"    padding-left:12px;\n"
"    border-radius:0px;\n"
"    border-left:2px solid transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-left:2px solid #40E0D0;\n"
"}")
        self.widget_long_menu.setObjectName("widget_long_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_long_menu)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_long_menu_menu = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_menu.setMinimumSize(QtCore.QSize(41, 31))
        self.btn_long_menu_menu.setMaximumSize(QtCore.QSize(41, 31))
        self.btn_long_menu_menu.setText("")
        self.btn_long_menu_menu.setIconSize(QtCore.QSize(24, 24))
        self.btn_long_menu_menu.setObjectName("btn_long_menu_menu")
        self.horizontalLayout_2.addWidget(self.btn_long_menu_menu)
        self.lbl_long_menu_header = QtWidgets.QLabel(parent=self.widget_long_menu)
        self.lbl_long_menu_header.setMinimumSize(QtCore.QSize(0, 38))
        self.lbl_long_menu_header.setMaximumSize(QtCore.QSize(16777215, 38))
        self.lbl_long_menu_header.setObjectName("lbl_long_menu_header")
        self.horizontalLayout_2.addWidget(self.lbl_long_menu_header)
        spacerItem4 = QtWidgets.QSpacerItem(40, 38, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(parent=self.widget_long_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout_4.addWidget(self.frame)
        self.btn_long_menu_copy = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_copy.setMinimumSize(QtCore.QSize(153, 31))
        self.btn_long_menu_copy.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_copy.setIcon(icon)
        self.btn_long_menu_copy.setObjectName("btn_long_menu_copy")
        self.verticalLayout_4.addWidget(self.btn_long_menu_copy)
        self.btn_long_menu_delete = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_delete.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_delete.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_delete.setIcon(icon1)
        self.btn_long_menu_delete.setObjectName("btn_long_menu_delete")
        self.verticalLayout_4.addWidget(self.btn_long_menu_delete)
        self.btn_long_menu_red = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_red.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_red.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_red.setIcon(icon2)
        self.btn_long_menu_red.setObjectName("btn_long_menu_red")
        self.verticalLayout_4.addWidget(self.btn_long_menu_red)
        self.btn_long_menu_rename = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_rename.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_rename.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_rename.setIcon(icon3)
        self.btn_long_menu_rename.setObjectName("btn_long_menu_rename")
        self.verticalLayout_4.addWidget(self.btn_long_menu_rename)
        self.btn_long_menu_count = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_count.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_count.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_count.setIcon(icon4)
        self.btn_long_menu_count.setObjectName("btn_long_menu_count")
        self.verticalLayout_4.addWidget(self.btn_long_menu_count)
        self.btn_long_menu_symlinks = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_symlinks.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_symlinks.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_symlinks.setIcon(icon5)
        self.btn_long_menu_symlinks.setObjectName("btn_long_menu_symlinks")
        self.verticalLayout_4.addWidget(self.btn_long_menu_symlinks)
        self.btn_long_menu_whoIs = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_whoIs.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_whoIs.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_whoIs.setIcon(icon6)
        self.btn_long_menu_whoIs.setObjectName("btn_long_menu_whoIs")
        self.verticalLayout_4.addWidget(self.btn_long_menu_whoIs)
        self.btn_long_menu_archive = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_archive.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_archive.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_archive.setIcon(icon7)
        self.btn_long_menu_archive.setObjectName("btn_long_menu_archive")
        self.verticalLayout_4.addWidget(self.btn_long_menu_archive)
        self.btn_long_menu_scenario = QtWidgets.QPushButton(parent=self.widget_long_menu)
        self.btn_long_menu_scenario.setMinimumSize(QtCore.QSize(0, 31))
        self.btn_long_menu_scenario.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_long_menu_scenario.setIcon(icon8)
        self.btn_long_menu_scenario.setIconSize(QtCore.QSize(16, 16))
        self.btn_long_menu_scenario.setObjectName("btn_long_menu_scenario")
        self.verticalLayout_4.addWidget(self.btn_long_menu_scenario)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.gridLayout_4.addWidget(self.widget_long_menu, 1, 1, 3, 1)
        self.stackedWidget_header = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget_header.setStyleSheet("QWidget{\n"
"    background-color:#EAEAEA;\n"
"}\n"
"\n"
"#lbl_fifsot_header, #lbl_upgrade_header, #lbl_problems_header, #lbl_status_header{\n"
"    font:24px;\n"
"}\n"
"\n"
"#btn_go_and_learn, #btn_go_version, #btn_let_us_know{\n"
"    background-color:#40E0D0;\n"
"}\n"
"\n"
"#btn_go_and_learn:hover, #btn_go_version:hover, #btn_let_us_know:hover{\n"
"    border:1px solid #2BA699;\n"
"}\n"
"\n"
"#btn_terminate_transactions{\n"
"    background-color:#FFFAFA;\n"
"    color:#FF0000;\n"
"}\n"
"\n"
"#btn_terminate_transactions:hover{\n"
"    background-color:#D3D3D3;\n"
"}\n"
"\n"
"#btn_terminate_transactions:pressed{\n"
"    border:3px solid transparent;\n"
"}")
        self.stackedWidget_header.setObjectName("stackedWidget_header")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_fifsot_header = QtWidgets.QLabel(parent=self.page)
        self.lbl_fifsot_header.setMinimumSize(QtCore.QSize(400, 30))
        self.lbl_fifsot_header.setMaximumSize(QtCore.QSize(400, 30))
        self.lbl_fifsot_header.setObjectName("lbl_fifsot_header")
        self.verticalLayout.addWidget(self.lbl_fifsot_header)
        self.lbl_hello_message = QtWidgets.QLabel(parent=self.page)
        self.lbl_hello_message.setMinimumSize(QtCore.QSize(400, 32))
        self.lbl_hello_message.setMaximumSize(QtCore.QSize(400, 32))
        self.lbl_hello_message.setWordWrap(True)
        self.lbl_hello_message.setObjectName("lbl_hello_message")
        self.verticalLayout.addWidget(self.lbl_hello_message)
        spacerItem6 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_go_and_learn = QtWidgets.QPushButton(parent=self.page)
        self.btn_go_and_learn.setMinimumSize(QtCore.QSize(170, 24))
        self.btn_go_and_learn.setMaximumSize(QtCore.QSize(170, 24))
        self.btn_go_and_learn.setObjectName("btn_go_and_learn")
        self.horizontalLayout_3.addWidget(self.btn_go_and_learn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.lbl_online_training = QtWidgets.QLabel(parent=self.page)
        self.lbl_online_training.setMinimumSize(QtCore.QSize(150, 100))
        self.lbl_online_training.setMaximumSize(QtCore.QSize(150, 100))
        self.lbl_online_training.setText("")
        self.lbl_online_training.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/online_training_2.png"))
        self.lbl_online_training.setScaledContents(True)
        self.lbl_online_training.setObjectName("lbl_online_training")
        self.horizontalLayout_4.addWidget(self.lbl_online_training)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.stackedWidget_header.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_upgrade_header = QtWidgets.QLabel(parent=self.page_2)
        self.lbl_upgrade_header.setMinimumSize(QtCore.QSize(400, 30))
        self.lbl_upgrade_header.setMaximumSize(QtCore.QSize(400, 30))
        self.lbl_upgrade_header.setObjectName("lbl_upgrade_header")
        self.verticalLayout_2.addWidget(self.lbl_upgrade_header)
        self.lbl_upgrade_message = QtWidgets.QLabel(parent=self.page_2)
        self.lbl_upgrade_message.setMinimumSize(QtCore.QSize(400, 32))
        self.lbl_upgrade_message.setMaximumSize(QtCore.QSize(400, 32))
        self.lbl_upgrade_message.setWordWrap(True)
        self.lbl_upgrade_message.setObjectName("lbl_upgrade_message")
        self.verticalLayout_2.addWidget(self.lbl_upgrade_message)
        spacerItem8 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_go_version = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_go_version.setMinimumSize(QtCore.QSize(170, 24))
        self.btn_go_version.setMaximumSize(QtCore.QSize(170, 24))
        self.btn_go_version.setObjectName("btn_go_version")
        self.horizontalLayout_6.addWidget(self.btn_go_version)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.lbl_update = QtWidgets.QLabel(parent=self.page_2)
        self.lbl_update.setMinimumSize(QtCore.QSize(150, 100))
        self.lbl_update.setMaximumSize(QtCore.QSize(150, 100))
        self.lbl_update.setText("")
        self.lbl_update.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/update_1.png"))
        self.lbl_update.setScaledContents(True)
        self.lbl_update.setObjectName("lbl_update")
        self.horizontalLayout_5.addWidget(self.lbl_update)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.stackedWidget_header.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_problems_header = QtWidgets.QLabel(parent=self.page_3)
        self.lbl_problems_header.setMinimumSize(QtCore.QSize(400, 30))
        self.lbl_problems_header.setMaximumSize(QtCore.QSize(400, 30))
        self.lbl_problems_header.setObjectName("lbl_problems_header")
        self.verticalLayout_3.addWidget(self.lbl_problems_header)
        self.lbl_problems_message = QtWidgets.QLabel(parent=self.page_3)
        self.lbl_problems_message.setMinimumSize(QtCore.QSize(400, 32))
        self.lbl_problems_message.setMaximumSize(QtCore.QSize(400, 32))
        self.lbl_problems_message.setWordWrap(True)
        self.lbl_problems_message.setObjectName("lbl_problems_message")
        self.verticalLayout_3.addWidget(self.lbl_problems_message)
        spacerItem10 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_let_us_know = QtWidgets.QPushButton(parent=self.page_3)
        self.btn_let_us_know.setMinimumSize(QtCore.QSize(170, 24))
        self.btn_let_us_know.setMaximumSize(QtCore.QSize(170, 24))
        self.btn_let_us_know.setObjectName("btn_let_us_know")
        self.horizontalLayout_9.addWidget(self.btn_let_us_know)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.lbl_problems = QtWidgets.QLabel(parent=self.page_3)
        self.lbl_problems.setMinimumSize(QtCore.QSize(150, 100))
        self.lbl_problems.setMaximumSize(QtCore.QSize(150, 100))
        self.lbl_problems.setText("")
        self.lbl_problems.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/bug_1.png"))
        self.lbl_problems.setScaledContents(True)
        self.lbl_problems.setObjectName("lbl_problems")
        self.horizontalLayout_8.addWidget(self.lbl_problems)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.stackedWidget_header.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbl_status_header = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_status_header.setMinimumSize(QtCore.QSize(430, 30))
        self.lbl_status_header.setMaximumSize(QtCore.QSize(380, 30))
        self.lbl_status_header.setObjectName("lbl_status_header")
        self.verticalLayout_7.addWidget(self.lbl_status_header)
        self.lbl_status_message = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_status_message.setMinimumSize(QtCore.QSize(430, 32))
        self.lbl_status_message.setMaximumSize(QtCore.QSize(430, 32))
        self.lbl_status_message.setWordWrap(True)
        self.lbl_status_message.setObjectName("lbl_status_message")
        self.verticalLayout_7.addWidget(self.lbl_status_message)
        self.lbl_status_message_2 = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_status_message_2.setMinimumSize(QtCore.QSize(430, 32))
        self.lbl_status_message_2.setMaximumSize(QtCore.QSize(430, 32))
        self.lbl_status_message_2.setWordWrap(True)
        self.lbl_status_message_2.setObjectName("lbl_status_message_2")
        self.verticalLayout_7.addWidget(self.lbl_status_message_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_7.addItem(spacerItem12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_terminate_transactions = QtWidgets.QPushButton(parent=self.page_4)
        self.btn_terminate_transactions.setMinimumSize(QtCore.QSize(170, 24))
        self.btn_terminate_transactions.setMaximumSize(QtCore.QSize(170, 24))
        self.btn_terminate_transactions.setObjectName("btn_terminate_transactions")
        self.horizontalLayout_13.addWidget(self.btn_terminate_transactions)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.lbl_status_icon = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_status_icon.setMinimumSize(QtCore.QSize(96, 96))
        self.lbl_status_icon.setMaximumSize(QtCore.QSize(96, 96))
        self.lbl_status_icon.setText("")
        self.lbl_status_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/completed_blue.png"))
        self.lbl_status_icon.setScaledContents(True)
        self.lbl_status_icon.setObjectName("lbl_status_icon")
        self.horizontalLayout_12.addWidget(self.lbl_status_icon)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.stackedWidget_header.addWidget(self.page_4)
        self.gridLayout_4.addWidget(self.stackedWidget_header, 1, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.radioButton_page_1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_page_1.setMinimumSize(QtCore.QSize(13, 13))
        self.radioButton_page_1.setMaximumSize(QtCore.QSize(13, 13))
        self.radioButton_page_1.setText("")
        self.radioButton_page_1.setIconSize(QtCore.QSize(16, 16))
        self.radioButton_page_1.setChecked(True)
        self.radioButton_page_1.setObjectName("radioButton_page_1")
        self.horizontalLayout_7.addWidget(self.radioButton_page_1)
        self.radioButton_page_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_page_2.setMinimumSize(QtCore.QSize(13, 13))
        self.radioButton_page_2.setMaximumSize(QtCore.QSize(13, 13))
        self.radioButton_page_2.setText("")
        self.radioButton_page_2.setObjectName("radioButton_page_2")
        self.horizontalLayout_7.addWidget(self.radioButton_page_2)
        self.radioButton_page_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_page_3.setMinimumSize(QtCore.QSize(13, 13))
        self.radioButton_page_3.setMaximumSize(QtCore.QSize(13, 13))
        self.radioButton_page_3.setText("")
        self.radioButton_page_3.setObjectName("radioButton_page_3")
        self.horizontalLayout_7.addWidget(self.radioButton_page_3)
        self.radioButton_page_4 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_page_4.setMinimumSize(QtCore.QSize(13, 13))
        self.radioButton_page_4.setMaximumSize(QtCore.QSize(13, 13))
        self.radioButton_page_4.setText("")
        self.radioButton_page_4.setObjectName("radioButton_page_4")
        self.horizontalLayout_7.addWidget(self.radioButton_page_4)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 2, 2, 1, 1)
        self.widget_scenario_space = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_scenario_space.setMinimumSize(QtCore.QSize(580, 370))
        self.widget_scenario_space.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_scenario_space.setStyleSheet("#widget_scenario_space{\n"
"    border:1px solid #101524;\n"
"    background-color:#D4D4D4;\n"
"}\n"
"\n"
"#lbl_your_scenarios_header{\n"
"    font:bold;\n"
"}\n"
"\n"
"#lbl_ready_to_use_scenarios_header{\n"
"    font:bold;\n"
"}")
        self.widget_scenario_space.setObjectName("widget_scenario_space")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_scenario_space)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_your_scenarios_header = QtWidgets.QLabel(parent=self.widget_scenario_space)
        self.lbl_your_scenarios_header.setMinimumSize(QtCore.QSize(550, 16))
        self.lbl_your_scenarios_header.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_your_scenarios_header.setObjectName("lbl_your_scenarios_header")
        self.verticalLayout_6.addWidget(self.lbl_your_scenarios_header)
        self.lbl_your_scenarios_text = QtWidgets.QLabel(parent=self.widget_scenario_space)
        self.lbl_your_scenarios_text.setMinimumSize(QtCore.QSize(550, 16))
        self.lbl_your_scenarios_text.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_your_scenarios_text.setObjectName("lbl_your_scenarios_text")
        self.verticalLayout_6.addWidget(self.lbl_your_scenarios_text)
        self.scrollArea_user_scenarios = QtWidgets.QScrollArea(parent=self.widget_scenario_space)
        self.scrollArea_user_scenarios.setMinimumSize(QtCore.QSize(560, 111))
        self.scrollArea_user_scenarios.setMaximumSize(QtCore.QSize(16777215, 111))
        self.scrollArea_user_scenarios.setStyleSheet("QScrollArea QWidget{\n"
"    background-color:#D4D4D4;\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border:none;\n"
"}")
        self.scrollArea_user_scenarios.setWidgetResizable(True)
        self.scrollArea_user_scenarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea_user_scenarios.setObjectName("scrollArea_user_scenarios")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 594, 111))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem16 = QtWidgets.QSpacerItem(573, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.scrollArea_user_scenarios.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_user_scenarios)
        self.frame_3 = QtWidgets.QFrame(parent=self.widget_scenario_space)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6.addWidget(self.frame_3)
        self.lbl_ready_to_use_scenarios_header = QtWidgets.QLabel(parent=self.widget_scenario_space)
        self.lbl_ready_to_use_scenarios_header.setMinimumSize(QtCore.QSize(550, 16))
        self.lbl_ready_to_use_scenarios_header.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_ready_to_use_scenarios_header.setObjectName("lbl_ready_to_use_scenarios_header")
        self.verticalLayout_6.addWidget(self.lbl_ready_to_use_scenarios_header)
        self.lbl_ready_to_use_scenarios_text = QtWidgets.QLabel(parent=self.widget_scenario_space)
        self.lbl_ready_to_use_scenarios_text.setMinimumSize(QtCore.QSize(550, 16))
        self.lbl_ready_to_use_scenarios_text.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_ready_to_use_scenarios_text.setObjectName("lbl_ready_to_use_scenarios_text")
        self.verticalLayout_6.addWidget(self.lbl_ready_to_use_scenarios_text)
        self.scrollArea_system_scenarios = QtWidgets.QScrollArea(parent=self.widget_scenario_space)
        self.scrollArea_system_scenarios.setMinimumSize(QtCore.QSize(560, 111))
        self.scrollArea_system_scenarios.setMaximumSize(QtCore.QSize(16777215, 111))
        self.scrollArea_system_scenarios.setStyleSheet("QScrollArea QWidget {\n"
"    background-color:#D4D4D4;\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border:none;\n"
"}")
        self.scrollArea_system_scenarios.setWidgetResizable(True)
        self.scrollArea_system_scenarios.setObjectName("scrollArea_system_scenarios")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 594, 111))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem17 = QtWidgets.QSpacerItem(573, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem17)
        self.scrollArea_system_scenarios.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea_system_scenarios)
        self.gridLayout_4.addWidget(self.widget_scenario_space, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_header.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_titlebar_text.setText(_translate("MainWindow", "FIFSOT v1.0.0 - Beta"))
        self.lbl_long_menu_header.setText(_translate("MainWindow", "Menu"))
        self.btn_long_menu_copy.setText(_translate("MainWindow", "Copy"))
        self.btn_long_menu_delete.setText(_translate("MainWindow", "Delete"))
        self.btn_long_menu_red.setText(_translate("MainWindow", "R.E.D."))
        self.btn_long_menu_rename.setText(_translate("MainWindow", "Rename"))
        self.btn_long_menu_count.setText(_translate("MainWindow", "Count"))
        self.btn_long_menu_symlinks.setText(_translate("MainWindow", "Symlinks"))
        self.btn_long_menu_whoIs.setText(_translate("MainWindow", "WhoIs?"))
        self.btn_long_menu_archive.setText(_translate("MainWindow", "Archive"))
        self.btn_long_menu_scenario.setText(_translate("MainWindow", "Scenario"))
        self.lbl_fifsot_header.setText(_translate("MainWindow", "FIFSOT"))
        self.lbl_hello_message.setText(_translate("MainWindow", "New here? Follow the link below for online user instructions, sample scenarios and much more."))
        self.btn_go_and_learn.setText(_translate("MainWindow", "Go and Learn"))
        self.lbl_upgrade_header.setText(_translate("MainWindow", "UPGRADE"))
        self.lbl_upgrade_message.setText(_translate("MainWindow", "Make sure you are always using the latest version. Updates include new features, bug fixes, and performance improvements."))
        self.btn_go_version.setText(_translate("MainWindow", "Check Now"))
        self.lbl_problems_header.setText(_translate("MainWindow", "PROBLEMS"))
        self.lbl_problems_message.setText(_translate("MainWindow", "If you encounter an unexpected error or an undesirable result, please let us know so we can fix the problem and improve the program."))
        self.btn_let_us_know.setText(_translate("MainWindow", "Let Us Know"))
        self.lbl_status_header.setText(_translate("MainWindow", "Everything is Done!"))
        self.lbl_status_message.setText(_translate("MainWindow", "You don\'t have any transactions that we are currently working on."))
        self.lbl_status_message_2.setText(_translate("MainWindow", "Waiting for None transactions..."))
        self.btn_terminate_transactions.setText(_translate("MainWindow", "Terminate All Transactions"))
        self.lbl_your_scenarios_header.setText(_translate("MainWindow", "Your Scenarios:"))
        self.lbl_your_scenarios_text.setText(_translate("MainWindow", "Below are the routines you have designed and saved."))
        self.lbl_ready_to_use_scenarios_header.setText(_translate("MainWindow", "Ready-to-Use Scenarios:"))
        self.lbl_ready_to_use_scenarios_text.setText(_translate("MainWindow", "Below are daily routines that we have left for your convenience."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
