# Form implementation generated from reading ui file 'pages\delete_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from ui_files import resources_rc

from Customs.CustomLineEdit import CustomLineEdit
QtWidgets.QLineEdit = CustomLineEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        MainWindow.resize(698, 461)
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:#F0F0F0;\n"
"    font:bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:#555555;\n"
"    border:1px solid #555555;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#F0F0F0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/checked_square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    image:url(\":/yeniÖnek/fifsot_icons/square.png\");\n"
"    width:16px;\n"
"    height:16px;\n"
"}\n"
"\n"
"#delete_header{\n"
"    color:#40E0D0;\n"
"    font:24px;\n"
"    padding:0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color:#101524;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_frame = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.widget_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_frame.setStyleSheet("QWidget[objectName=\"widget_frame\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:none;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    color:#FFFFFF;\n"
"}\n"
"\n"
"#lbl_titlebar_text{\n"
"    font:12px;\n"
"}\n"
"\n"
"#btn_close_window{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}\n"
"\n"
"#btn_close_window:hover{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_red.png\");\n"
"}\n"
"\n"
"#btn_close_window:pressed{\n"
"    icon:url(\":/yeniÖnek/fifsot_icons/close_1_white.png\");\n"
"}")
        self.widget_frame.setObjectName("widget_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_titlebar_icon = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.lbl_titlebar_icon.setText("")
        self.lbl_titlebar_icon.setPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/F_Icon_1.png"))
        self.lbl_titlebar_icon.setScaledContents(True)
        self.lbl_titlebar_icon.setObjectName("lbl_titlebar_icon")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_icon)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lbl_titlebar_text = QtWidgets.QLabel(parent=self.widget_frame)
        self.lbl_titlebar_text.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_titlebar_text.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbl_titlebar_text.setObjectName("lbl_titlebar_text")
        self.horizontalLayout_7.addWidget(self.lbl_titlebar_text)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btn_close_window = QtWidgets.QPushButton(parent=self.widget_frame)
        self.btn_close_window.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_window.setText("")
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_7.addWidget(self.btn_close_window)
        self.gridLayout_3.addWidget(self.widget_frame, 0, 0, 1, 1)
        self.delete_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.delete_header.setMinimumSize(QtCore.QSize(590, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.delete_header.setFont(font)
        self.delete_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.delete_header.setObjectName("delete_header")
        self.gridLayout_3.addWidget(self.delete_header, 1, 0, 1, 1)
        self.delete_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.delete_text.setMinimumSize(QtCore.QSize(590, 25))
        self.delete_text.setIndent(16)
        self.delete_text.setObjectName("delete_text")
        self.gridLayout_3.addWidget(self.delete_text, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_address = QtWidgets.QLabel(parent=self.widget)
        self.lbl_address.setMinimumSize(QtCore.QSize(75, 20))
        self.lbl_address.setMaximumSize(QtCore.QSize(75, 20))
        self.lbl_address.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_address.setObjectName("lbl_address")
        self.horizontalLayout.addWidget(self.lbl_address)
        self.lineEdit_address = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_address.setMinimumSize(QtCore.QSize(430, 25))
        self.lineEdit_address.setClearButtonEnabled(True)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout.addWidget(self.lineEdit_address)
        self.btn_openDialog_address = QtWidgets.QPushButton(parent=self.widget)
        self.btn_openDialog_address.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yeniÖnek/fifsot_icons/open_file_dialog.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_openDialog_address.setIcon(icon)
        self.btn_openDialog_address.setIconSize(QtCore.QSize(20, 20))
        self.btn_openDialog_address.setObjectName("btn_openDialog_address")
        self.horizontalLayout.addWidget(self.btn_openDialog_address)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(8, -1, -1, -1)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_onlyContent = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_onlyContent.setMinimumSize(QtCore.QSize(0, 16))
        self.checkBox_onlyContent.setMaximumSize(QtCore.QSize(16777215, 16))
        self.checkBox_onlyContent.setChecked(True)
        self.checkBox_onlyContent.setObjectName("checkBox_onlyContent")
        self.gridLayout.addWidget(self.checkBox_onlyContent, 1, 0, 1, 1)
        self.checkBox_deleteObjectsInSymlinks = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_deleteObjectsInSymlinks.setMinimumSize(QtCore.QSize(0, 16))
        self.checkBox_deleteObjectsInSymlinks.setMaximumSize(QtCore.QSize(16777215, 16))
        self.checkBox_deleteObjectsInSymlinks.setObjectName("checkBox_deleteObjectsInSymlinks")
        self.gridLayout.addWidget(self.checkBox_deleteObjectsInSymlinks, 0, 1, 1, 1)
        self.checkBox_followSymlinks = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_followSymlinks.setMinimumSize(QtCore.QSize(0, 16))
        self.checkBox_followSymlinks.setMaximumSize(QtCore.QSize(16777215, 16))
        self.checkBox_followSymlinks.setObjectName("checkBox_followSymlinks")
        self.gridLayout.addWidget(self.checkBox_followSymlinks, 0, 2, 1, 1)
        self.checkBox_recursive = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_recursive.setMinimumSize(QtCore.QSize(0, 16))
        self.checkBox_recursive.setMaximumSize(QtCore.QSize(16777215, 16))
        self.checkBox_recursive.setChecked(True)
        self.checkBox_recursive.setObjectName("checkBox_recursive")
        self.gridLayout.addWidget(self.checkBox_recursive, 1, 1, 1, 1)
        self.checkBox_onlyFiles = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_onlyFiles.setMinimumSize(QtCore.QSize(0, 16))
        self.checkBox_onlyFiles.setMaximumSize(QtCore.QSize(16777215, 16))
        self.checkBox_onlyFiles.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_onlyFiles.setObjectName("checkBox_onlyFiles")
        self.gridLayout.addWidget(self.checkBox_onlyFiles, 0, 0, 1, 1)
        self.checkBox_forcePermission = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_forcePermission.setMinimumSize(QtCore.QSize(0, 16))
        self.checkBox_forcePermission.setMaximumSize(QtCore.QSize(16777215, 16))
        self.checkBox_forcePermission.setChecked(True)
        self.checkBox_forcePermission.setObjectName("checkBox_forcePermission")
        self.gridLayout.addWidget(self.checkBox_forcePermission, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.lbl_conditions = QtWidgets.QLabel(parent=self.widget)
        self.lbl_conditions.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_conditions.setObjectName("lbl_conditions")
        self.verticalLayout.addWidget(self.lbl_conditions)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_extension = QtWidgets.QLabel(parent=self.widget)
        self.lbl_extension.setMinimumSize(QtCore.QSize(105, 20))
        self.lbl_extension.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_extension.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_extension.setObjectName("lbl_extension")
        self.horizontalLayout_3.addWidget(self.lbl_extension)
        self.lineEdit_extension = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_extension.setMinimumSize(QtCore.QSize(204, 25))
        self.lineEdit_extension.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_extension.setClearButtonEnabled(True)
        self.lineEdit_extension.setObjectName("lineEdit_extension")
        self.horizontalLayout_3.addWidget(self.lineEdit_extension)
        self.lbl_excludeNameStartswith = QtWidgets.QLabel(parent=self.widget)
        self.lbl_excludeNameStartswith.setMinimumSize(QtCore.QSize(145, 20))
        self.lbl_excludeNameStartswith.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_excludeNameStartswith.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_excludeNameStartswith.setObjectName("lbl_excludeNameStartswith")
        self.horizontalLayout_3.addWidget(self.lbl_excludeNameStartswith)
        self.lineEdit_excludeNameStartswith = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_excludeNameStartswith.setMinimumSize(QtCore.QSize(204, 25))
        self.lineEdit_excludeNameStartswith.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_excludeNameStartswith.setClearButtonEnabled(True)
        self.lineEdit_excludeNameStartswith.setObjectName("lineEdit_excludeNameStartswith")
        self.horizontalLayout_3.addWidget(self.lineEdit_excludeNameStartswith)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_nameStartswith = QtWidgets.QLabel(parent=self.widget)
        self.lbl_nameStartswith.setMinimumSize(QtCore.QSize(105, 20))
        self.lbl_nameStartswith.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_nameStartswith.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_nameStartswith.setObjectName("lbl_nameStartswith")
        self.horizontalLayout_4.addWidget(self.lbl_nameStartswith)
        self.lineEdit_nameStartswith = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_nameStartswith.setMinimumSize(QtCore.QSize(204, 25))
        self.lineEdit_nameStartswith.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_nameStartswith.setClearButtonEnabled(True)
        self.lineEdit_nameStartswith.setObjectName("lineEdit_nameStartswith")
        self.horizontalLayout_4.addWidget(self.lineEdit_nameStartswith)
        self.lbl_excludeNameContains = QtWidgets.QLabel(parent=self.widget)
        self.lbl_excludeNameContains.setMinimumSize(QtCore.QSize(145, 20))
        self.lbl_excludeNameContains.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_excludeNameContains.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_excludeNameContains.setIndent(2)
        self.lbl_excludeNameContains.setObjectName("lbl_excludeNameContains")
        self.horizontalLayout_4.addWidget(self.lbl_excludeNameContains)
        self.lineEdit_excludeNameContains = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_excludeNameContains.setMinimumSize(QtCore.QSize(204, 25))
        self.lineEdit_excludeNameContains.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_excludeNameContains.setClearButtonEnabled(True)
        self.lineEdit_excludeNameContains.setObjectName("lineEdit_excludeNameContains")
        self.horizontalLayout_4.addWidget(self.lineEdit_excludeNameContains)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_nameContains = QtWidgets.QLabel(parent=self.widget)
        self.lbl_nameContains.setMinimumSize(QtCore.QSize(105, 20))
        self.lbl_nameContains.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_nameContains.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_nameContains.setObjectName("lbl_nameContains")
        self.horizontalLayout_5.addWidget(self.lbl_nameContains)
        self.lineEdit_nameContains = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_nameContains.setMinimumSize(QtCore.QSize(204, 25))
        self.lineEdit_nameContains.setMaximumSize(QtCore.QSize(204, 25))
        self.lineEdit_nameContains.setClearButtonEnabled(True)
        self.lineEdit_nameContains.setObjectName("lineEdit_nameContains")
        self.horizontalLayout_5.addWidget(self.lineEdit_nameContains)
        self.checkBox_caseInsensitive = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_caseInsensitive.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_caseInsensitive.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_caseInsensitive.setObjectName("checkBox_caseInsensitive")
        self.horizontalLayout_5.addWidget(self.checkBox_caseInsensitive)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 3, 0, 1, 1)
        self.widget_btn_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_btn_container.setMinimumSize(QtCore.QSize(430, 50))
        self.widget_btn_container.setStyleSheet("QWidget[objectName=\"widget_btn_container\"]{\n"
"    background-color:#3B3B3B;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#40E0D0;\n"
"    border:2px solid #40E0D0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:2px solid #2BA699;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:#555555;\n"
"}")
        self.widget_btn_container.setObjectName("widget_btn_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_btn_container)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(303, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.btn_delete = QtWidgets.QPushButton(parent=self.widget_btn_container)
        self.btn_delete.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_delete.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_6.addWidget(self.btn_delete)
        self.gridLayout_3.addWidget(self.widget_btn_container, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DeleteWindow"))
        self.lbl_titlebar_text.setText(_translate("MainWindow", "Delete"))
        self.delete_header.setText(_translate("MainWindow", "Delete"))
        self.delete_text.setText(_translate("MainWindow", "Delete whatever you want, with comprehensive filters."))
        self.lbl_address.setText(_translate("MainWindow", "Address:"))
        self.lineEdit_address.setPlaceholderText(_translate("MainWindow", "Select or drag and drop"))
        self.checkBox_onlyContent.setText(_translate("MainWindow", "Only Content"))
        self.checkBox_deleteObjectsInSymlinks.setText(_translate("MainWindow", "Delete Objects in Symlinks"))
        self.checkBox_followSymlinks.setText(_translate("MainWindow", "Follow Symlinks"))
        self.checkBox_recursive.setText(_translate("MainWindow", "Recursive"))
        self.checkBox_onlyFiles.setText(_translate("MainWindow", "Only Files"))
        self.checkBox_forcePermission.setText(_translate("MainWindow", "Force Permissions"))
        self.lbl_conditions.setText(_translate("MainWindow", "Conditions"))
        self.lbl_extension.setText(_translate("MainWindow", "Extension:"))
        self.lineEdit_extension.setPlaceholderText(_translate("MainWindow", "--All--"))
        self.lbl_excludeNameStartswith.setText(_translate("MainWindow", "Exclude Name Startswith:"))
        self.lineEdit_excludeNameStartswith.setPlaceholderText(_translate("MainWindow", "--None--"))
        self.lbl_nameStartswith.setText(_translate("MainWindow", "Name Startswith:"))
        self.lineEdit_nameStartswith.setPlaceholderText(_translate("MainWindow", "--All--"))
        self.lbl_excludeNameContains.setText(_translate("MainWindow", "Exclude Name Contains:"))
        self.lineEdit_excludeNameContains.setPlaceholderText(_translate("MainWindow", "--None--"))
        self.lbl_nameContains.setText(_translate("MainWindow", "Name Contains:"))
        self.lineEdit_nameContains.setPlaceholderText(_translate("MainWindow", "--All--"))
        self.checkBox_caseInsensitive.setText(_translate("MainWindow", "Case Insensitive"))
        self.btn_delete.setText(_translate("MainWindow", "Delete Now"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
